"""initial schema (F0.6)

Revision ID: 5d50b03281c3
Revises: 
Create Date: 2026-06-01 22:05:57.035678
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d50b03281c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_entity_type'), ['entity_type'], unique=False)

    op.create_table('run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sa.Enum('SINGLE_COMPANY', 'DISCOVERY', name='executionmode', native_enum=False, length=40), nullable=False),
    sa.Column('hitl', sa.Enum('SYNC', 'AUTO', name='hitlmode', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'AWAITING_REVIEW', 'COMPLETED', 'INSUFFICIENT_DATA', 'OUT_OF_SCOPE', 'FAILED', name='runstatus', native_enum=False, length=40), nullable=False),
    sa.Column('briefing_status', sa.Enum('NORMAL', 'DADOS_INSUFICIENTES', 'FORA_DE_ESCOPO', name='briefingstatus', native_enum=False, length=40), nullable=True),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pais', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('setor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ano_fundacao', sa.Integer(), nullable=True),
    sa.Column('produtos', sa.JSON(), nullable=True),
    sa.Column('clientes', sa.JSON(), nullable=True),
    sa.Column('tecnologias', sa.JSON(), nullable=True),
    sa.Column('funding', sa.JSON(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'pais', name='uq_company_nome_pais')
    )
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_pais'), ['pais'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_company_setor'), ['setor'], unique=False)

    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cargo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linkedin_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_founder_company_id'), ['company_id'], unique=False)

    op.create_table('recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tech', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('justificativa_tecnica', sa.Text(), nullable=True),
    sa.Column('justificativa_negocio', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.Enum('ALTA', 'MEDIA', 'BAIXA', name='priority', native_enum=False, length=40), nullable=False),
    sa.Column('complexidade', sa.Enum('BAIXA', 'MEDIA', 'ALTA', name='complexity', native_enum=False, length=40), nullable=False),
    sa.Column('proxima_acao', sa.Text(), nullable=True),
    sa.Column('pilar_origem', sa.Enum('DATA_MOAT', 'WORKFLOW_DEPTH', 'TECHNICAL_OPTIMIZATION', 'DISTRIBUTION_MOAT', name='aimipillar', native_enum=False, length=40), nullable=True),
    sa.Column('roi', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_tech'), ['tech'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('classificacao', sa.Enum('AI_NATIVE', 'AI_ENABLED', 'NON_AI', name='classification', native_enum=False, length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('inception_priority', sa.Integer(), nullable=True),
    sa.Column('heuristic_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_moat', sa.Integer(), nullable=False),
    sa.Column('workflow_depth', sa.Integer(), nullable=False),
    sa.Column('technical_optimization', sa.Integer(), nullable=False),
    sa.Column('distribution_moat', sa.Integer(), nullable=False),
    sa.Column('just_data_moat', sa.Text(), nullable=True),
    sa.Column('just_workflow_depth', sa.Text(), nullable=True),
    sa.Column('just_technical_optimization', sa.Text(), nullable=True),
    sa.Column('just_distribution_moat', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_run_id'))
        batch_op.drop_index(batch_op.f('ix_score_company_id'))

    op.drop_table('score')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_tech'))
        batch_op.drop_index(batch_op.f('ix_recommendation_run_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_company_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('founder', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_founder_company_id'))

    op.drop_table('founder')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_setor'))
        batch_op.drop_index(batch_op.f('ix_company_run_id'))
        batch_op.drop_index(batch_op.f('ix_company_pais'))
        batch_op.drop_index(batch_op.f('ix_company_nome'))

    op.drop_table('company')
    op.drop_table('run')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_entity_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_entity_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_content_hash'))

    op.drop_table('evidence')
    # ### end Alembic commands ###
