from __future__ import annotations

from app.core.schemas import KnowledgeSourceInput


NVIDIA_KNOWLEDGE_SOURCES = [
    KnowledgeSourceInput(
        titulo="NVIDIA NIM Documentation",
        url="https://docs.nvidia.com/nim/",
        tecnologia="NIM",
        tipo="documentacao",
        dores_relacionadas=["custo", "latencia", "escalabilidade", "vendor_lockin"],
        perfil_aplicavel=["AI-native", "AI-enabled", "API-consumer"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Triton Inference Server Documentation",
        url="https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/",
        tecnologia="Triton",
        tipo="documentacao",
        dores_relacionadas=["custo", "latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA TensorRT-LLM Documentation",
        url="https://docs.nvidia.com/tensorrt-llm/",
        tecnologia="TensorRT-LLM",
        tipo="documentacao",
        dores_relacionadas=["custo", "latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA NeMo Documentation",
        url="https://docs.nvidia.com/nemo/",
        tecnologia="NeMo",
        tipo="documentacao",
        dores_relacionadas=["governanca", "privacidade", "vendor_lockin"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA RAPIDS Documentation",
        url="https://docs.rapids.ai/",
        tecnologia="RAPIDS",
        tipo="documentacao",
        dores_relacionadas=["custo", "latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="CUDA Toolkit Documentation",
        url="https://docs.nvidia.com/cuda/",
        tecnologia="CUDA",
        tipo="documentacao",
        dores_relacionadas=["latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Riva Documentation",
        url="https://docs.nvidia.com/deeplearning/riva/user-guide/docs/",
        tecnologia="Riva",
        tipo="documentacao",
        dores_relacionadas=["latencia", "escalabilidade", "privacidade"],
        perfil_aplicavel=["AI-native", "AI-enabled", "API-consumer"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Omniverse Documentation",
        url="https://docs.omniverse.nvidia.com/",
        tecnologia="Omniverse",
        tipo="documentacao",
        dores_relacionadas=["escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Clara",
        url="https://www.nvidia.com/en-us/clara/",
        tecnologia="Clara",
        tipo="documentacao",
        dores_relacionadas=["governanca", "privacidade", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Isaac",
        url="https://developer.nvidia.com/isaac",
        tecnologia="Isaac",
        tipo="documentacao",
        dores_relacionadas=["latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Morpheus Documentation",
        url="https://docs.nvidia.com/morpheus/",
        tecnologia="Morpheus",
        tipo="documentacao",
        dores_relacionadas=["governanca", "privacidade", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA AI Enterprise Documentation",
        url="https://docs.nvidia.com/ai-enterprise/",
        tecnologia="AI Enterprise",
        tipo="documentacao",
        dores_relacionadas=["governanca", "privacidade", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Inception",
        url="https://www.nvidia.com/en-us/startups/",
        tecnologia="Inception",
        tipo="documentacao",
        dores_relacionadas=["custo", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled", "API-consumer"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Developer Technical Blog",
        url="https://developer.nvidia.com/blog/tag/generative-ai/",
        tecnologia="NIM",
        tipo="blog",
        dores_relacionadas=["custo", "latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA Triton GitHub",
        url="https://github.com/triton-inference-server/server",
        tecnologia="Triton",
        tipo="github",
        dores_relacionadas=["latencia", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled"],
    ),
    KnowledgeSourceInput(
        titulo="NVIDIA AI Resources",
        url="https://resources.nvidia.com/en-us-ai",
        tecnologia="AI Enterprise",
        tipo="whitepaper",
        dores_relacionadas=["governanca", "privacidade", "escalabilidade"],
        perfil_aplicavel=["AI-native", "AI-enabled", "API-consumer"],
    ),
]
