/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupIdRouteImport } from './routes/startup.$id'

const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupIdRoute = StartupIdRouteImport.update({
  id: '/startup/$id',
  path: '/startup/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/sources': typeof SourcesRoute
  '/startup/$id': typeof StartupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/sources': typeof SourcesRoute
  '/startup/$id': typeof StartupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/contacts': typeof ContactsRoute
  '/pipeline': typeof PipelineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/sources': typeof SourcesRoute
  '/startup/$id': typeof StartupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefing'
    | '/contacts'
    | '/pipeline'
    | '/profile'
    | '/ranking'
    | '/sources'
    | '/startup/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefing'
    | '/contacts'
    | '/pipeline'
    | '/profile'
    | '/ranking'
    | '/sources'
    | '/startup/$id'
  id:
    | '__root__'
    | '/'
    | '/briefing'
    | '/contacts'
    | '/pipeline'
    | '/profile'
    | '/ranking'
    | '/sources'
    | '/startup/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  ContactsRoute: typeof ContactsRoute
  PipelineRoute: typeof PipelineRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  SourcesRoute: typeof SourcesRoute
  StartupIdRoute: typeof StartupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startup/$id': {
      id: '/startup/$id'
      path: '/startup/$id'
      fullPath: '/startup/$id'
      preLoaderRoute: typeof StartupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  ContactsRoute: ContactsRoute,
  PipelineRoute: PipelineRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  SourcesRoute: SourcesRoute,
  StartupIdRoute: StartupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
