-- Remove colunas sem qualquer valor útil nos 398 registros auditados.
ALTER TABLE startup_ai_radar_catalog
    DROP COLUMN IF EXISTS company_description,
    DROP COLUMN IF EXISTS validated_url,
    DROP COLUMN IF EXISTS website_candidate,
    DROP COLUMN IF EXISTS website_confidence,
    DROP COLUMN IF EXISTS github_org,
    DROP COLUMN IF EXISTS linkedin_url,
    DROP COLUMN IF EXISTS crunchbase_url,
    DROP COLUMN IF EXISTS gupy_url,
    DROP COLUMN IF EXISTS tech_stack,
    DROP COLUMN IF EXISTS ai_integrations,
    DROP COLUMN IF EXISTS open_jobs_signals,
    DROP COLUMN IF EXISTS rejected_urls,
    DROP COLUMN IF EXISTS validated_urls,
    DROP COLUMN IF EXISTS candidate_urls,
    DROP COLUMN IF EXISTS candidate_attempts,
    DROP COLUMN IF EXISTS identity_evidence,
    DROP COLUMN IF EXISTS tech_confidence_score,
    DROP COLUMN IF EXISTS identity_confidence_score,
    DROP COLUMN IF EXISTS discard_reason,
    DROP COLUMN IF EXISTS last_enriched_at,
    DROP COLUMN IF EXISTS github_candidatos_testados,
    DROP COLUMN IF EXISTS github_repo_validado,
    DROP COLUMN IF EXISTS github_validacao_evidencia,
    DROP COLUMN IF EXISTS github_validacao_criterios,
    DROP COLUMN IF EXISTS sector;
