#!/usr/bin/env python3
from __future__ import annotations
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];R=ROOT/'registry'
proto=json.loads((R/'w4c_saturation_gate_protocol_v1.json').read_text());plan=json.loads((R/'w4_maximal_backtest_research_plan_v1.json').read_text());sources=json.loads((R/'w4_maximal_data_source_registry_v1.json').read_text());families=json.loads((R/'w4_family_expansion_research_v1.json').read_text());attr=json.loads((R/'w4b_attrition_summary_v1.json').read_text());ot=json.loads((R/'w4b_official_event_truth_summary_v1.json').read_text())
assert proto['version']=='W4C-SAT-v1.0' and proto['status']=='PREREGISTERED_AFTER_W4B_ATTRITION_BEFORE_W4C_GATE_EXECUTION'
assert plan['science_reopened'] is False and plan['performance_blind'] is True
assert attr['gate_decision']=='PASS_W4B_ATTRITION_MATERIALIZED' and all(attr['conservation_checks'].values()) and attr['n_final_backtestable_authorized'] is False and attr['linked_asset_realized_returns_read'] is False
assert ot['gate_decision']=='PASS_OFFICIAL_EVENT_TRUTH_MATERIALIZED' and ot['performance_blind'] is True and ot['linked_asset_realized_returns_read'] is False
src=sources['sources'];by_id={x['id']:x for x in src};rp={x['id']:x for x in proto['route_tests']}
expected={'R1_OFFICIAL_TRUTH_EXTENSION','R2_POLYMARKET_PIT_HISTORY','R3_FORECASTEX_PIT_HISTORY','R4_P0_FAMILY_EXPANSION','R5_POLYMARKET_V1_ARCHIVE','R6_P1_PRIMARY_VENUE_ACCESS','R7_ROBUSTNESS_VENUE'};assert set(rp)==expected
rows=[]
def add(i,o,e,q,n=''):
 p=rp[i];rows.append({'route_id':i,'priority_rank':p['priority_rank'],'is_open':'YES' if o else 'NO','dimensions':'|'.join(p['dimension']),'evidence':e,'quantitative_capacity_or_gap':q,'required_new_freeze':p['required_new_freeze'],'note':n})
unresolved=int(ot['verification_state_counts'].get('UNRESOLVED_OFFICIAL_TRUTH',0));truth=[s for s in src if s.get('layer')=='event_truth_primary' and s.get('status','').startswith('P0_')]
add('R1_OFFICIAL_TRUTH_EXTENSION',unresolved>0 and bool(truth),f'unresolved_official_truth={unresolved};registered_P0_event_truth_sources={len(truth)}',str(unresolved),'Any extension is new W4-C evidence; frozen W4-B truth stays unchanged.')
pm=int(attr['polymarket_canonical_census_events']);add('R2_POLYMARKET_PIT_HISTORY',pm>0 and attr['polymarket_backtestable_claim_authorized'] is False,f'polymarket_canonical_census_events={pm};backtestable_authorized={attr["polymarket_backtestable_claim_authorized"]}',str(pm),'PIT qualification can only qualify/reduce capacity; contracts never become pseudo-N.')
fx=int(attr['forecastex_canonical_census_events']);add('R3_FORECASTEX_PIT_HISTORY',fx>0 and attr['forecastex_backtestable_claim_authorized'] is False,f'forecastex_canonical_census_events={fx};backtestable_authorized={attr["forecastex_backtestable_claim_authorized"]}',str(fx))
p0=[x for x in families['priority_candidates'] if x.get('priority')=='P0' and x.get('gate')=='P0_FAMILY_CENSUS'];add('R4_P0_FAMILY_EXPANSION',bool(p0),'P0_candidates='+'|'.join(x['family'] for x in p0),str(len(p0)),'Original W4-B family dictionary remains immutable.')
pmv1=by_id.get('POLYMARKET_V1_ARCHIVE',{});add('R5_POLYMARKET_V1_ARCHIVE',pmv1.get('status')=='P0_ARCHIVE_ACCESS_GATE',f'status={pmv1.get("status","")};depth_gain={pmv1.get("depth_gain","")};reproducibility={pmv1.get("reproducibility","")}',pmv1.get('historical_depth',''),'Archive cannot override official identifiers or semantics.')
p1=[s for s in src if s.get('layer')=='prediction_market_primary' and s.get('status')=='P1_DATA_ACCESS_GATE' and (str(s.get('independent_n_gain','')).upper() not in {'NONE','INDIRECT_DISCOVERY_ONLY'} or str(s.get('breadth_gain','')).upper() not in {'NONE','LOW'})];add('R6_P1_PRIMARY_VENUE_ACCESS',bool(p1),'P1_primary_sources='+'|'.join(s['id'] for s in p1),str(len(p1)),'Designation/listing alone never counts as backtestable population.')
rob=[s for s in src if s.get('layer')=='prediction_market_robustness' and s.get('status')=='P1_ROBUSTNESS_ONLY' and ('HIGH' in str(s.get('depth_gain','')).upper() or 'HIGH' in str(s.get('breadth_gain','')).upper() or 'HIGH' in str(s.get('independent_n_gain','')).upper())];add('R7_ROBUSTNESS_VENUE',bool(rob),'robustness_sources='+'|'.join(s['id'] for s in rob),str(len(rob)),'External-validity breadth is separate from primary independent N.')
rows.sort(key=lambda x:int(x['priority_rank']));openr=[r for r in rows if r['is_open']=='YES'];sat=not openr;decision='STOP_SATURATED' if sat else 'CONTINUE_EXPANSION_NOT_SATURATED';gate='PASS_W4C_SATURATION_GATE_STOP' if sat else 'PASS_W4C_SATURATION_GATE_CONTINUE'
fields=['route_id','priority_rank','is_open','dimensions','evidence','quantitative_capacity_or_gap','required_new_freeze','note']
with (R/'w4c_saturation_route_audit_v1.csv').open('w',encoding='utf-8',newline='') as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
out={'artifact':'W4C_SATURATION_GATE_SUMMARY','version':'W4C-SAT-RESULT-v1.0','protocol_version':proto['version'],'decision':decision,'gate_decision':gate,'saturated':sat,'route_tests_total':len(rows),'open_material_routes':len(openr),'open_route_ids':[r['route_id'] for r in openr],'next_priority_route':openr[0]['route_id'] if openr else None,'w4b_truth_verified_unique_official_events_immutable':int(attr['truth_verified_unique_official_events']),'w4b_pretruth_exact_groups':int(attr['pretruth_exact_cross_venue_groups']),'w4b_polymarket_census_capacity':pm,'w4b_forecastex_census_capacity':fx,'n_final_backtestable_authorized':False,'outcome_reveal_authorized':False,'science_reopened':False,'performance_blind':True,'linked_asset_realized_returns_read':False,'prediction_market_performance_read':False,'interpretation':'W4-C applies the preregistered continue-if-any saturation rule to frozen W4-B attrition and pre-outcome source/family registries. CONTINUE preserves W4-B and requires separately frozen extension routes; it does not authorize N_final_backtestable or outcome reveal.'}
(R/'w4c_saturation_summary_v1.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True))
