"""create scraping tables

Revision ID: f3f7f3959ccc
Revises: 
Create Date: 2026-06-13 21:37:54.111657
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Identificador único desta migration.
revision: str = 'f3f7f3959ccc'

# Migration anterior, na qual esta se baseia. None se for a primeira.
down_revision: Union[str, None] = None

# Usados quando há ramificações no histórico de migrations (não é o nosso
# caso por enquanto, mas o Alembic exige que estes nomes existam).
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica esta migration (avança o schema)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraping_jobs'))
    )
    op.create_index(op.f('ix_scraping_jobs_status'), 'scraping_jobs', ['status'], unique=False)
    op.create_table('scraping_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('evidence_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('problems', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('evidence_score BETWEEN 0 AND 1', name=op.f('ck_scraping_attempts_evidence_score_range')),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 1', name=op.f('ck_scraping_attempts_quality_score_range')),
    sa.CheckConstraint('technical_score BETWEEN 0 AND 1', name=op.f('ck_scraping_attempts_technical_score_range')),
    sa.CheckConstraint('text_score BETWEEN 0 AND 1', name=op.f('ck_scraping_attempts_text_score_range')),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], name=op.f('fk_scraping_attempts_job_id_scraping_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraping_attempts'))
    )
    op.create_index(op.f('ix_scraping_attempts_job_id'), 'scraping_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_scraping_attempts_started_at'), 'scraping_attempts', ['started_at'], unique=False)
    op.create_index(op.f('ix_scraping_attempts_status'), 'scraping_attempts', ['status'], unique=False)
    op.create_table('scraping_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('text_score', sa.Float(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('evidence_score BETWEEN 0 AND 1', name=op.f('ck_scraping_results_evidence_score_range')),
    sa.CheckConstraint('quality_score BETWEEN 0 AND 1', name=op.f('ck_scraping_results_quality_score_range')),
    sa.CheckConstraint('status_code BETWEEN 100 AND 599', name=op.f('ck_scraping_results_status_code_range')),
    sa.CheckConstraint('technical_score BETWEEN 0 AND 1', name=op.f('ck_scraping_results_technical_score_range')),
    sa.CheckConstraint('text_score BETWEEN 0 AND 1', name=op.f('ck_scraping_results_text_score_range')),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], name=op.f('fk_scraping_results_job_id_scraping_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraping_results'))
    )
    op.create_index(op.f('ix_scraping_results_content_hash'), 'scraping_results', ['content_hash'], unique=False)
    op.create_index(op.f('ix_scraping_results_job_id'), 'scraping_results', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Desfaz esta migration (volta o schema ao estado anterior)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_results_job_id'), table_name='scraping_results')
    op.drop_index(op.f('ix_scraping_results_content_hash'), table_name='scraping_results')
    op.drop_table('scraping_results')
    op.drop_index(op.f('ix_scraping_attempts_status'), table_name='scraping_attempts')
    op.drop_index(op.f('ix_scraping_attempts_started_at'), table_name='scraping_attempts')
    op.drop_index(op.f('ix_scraping_attempts_job_id'), table_name='scraping_attempts')
    op.drop_table('scraping_attempts')
    op.drop_index(op.f('ix_scraping_jobs_status'), table_name='scraping_jobs')
    op.drop_table('scraping_jobs')
    # ### end Alembic commands ###
