"""create all product entities

Revision ID: e0d3e59b52e5
Revises:
Create Date: 2026-06-12 12:39:28.957928
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e0d3e59b52e5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "startups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("normalized_name", sa.String(length=255), nullable=False),
        sa.Column("website", sa.String(length=2048), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("sector", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("product_summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_name"),
    )
    with op.batch_alter_table("startups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_startups_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_startups_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_startups_status"), ["status"], unique=False)

    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("startup_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("degraded_reason", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("input_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("output_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("pipeline_version", sa.String(length=100), nullable=False),
        sa.Column("corpus_version", sa.String(length=100), nullable=True),
        sa.Column("config_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["startup_id"], ["startups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_runs_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_analysis_runs_startup_created", ["startup_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_runs_startup_id"), ["startup_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_analysis_runs_status"), ["status"], unique=False)

    op.create_table(
        "startup_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("startup_id", sa.String(length=36), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=2048), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("quote_or_evidence", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("evidence_kind", sa.String(length=50), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["startup_id"], ["startups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("startup_evidence", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_startup_evidence_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_startup_evidence_evidence_kind"), ["evidence_kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_startup_evidence_source_url"), ["source_url"], unique=False)
        batch_op.create_index("ix_startup_evidence_startup_collected", ["startup_id", "collected_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_startup_evidence_startup_id"), ["startup_id"], unique=False)

    op.create_table(
        "action_brief_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=50), nullable=False),
        sa.Column("brief_json", sa.JSON(), nullable=False),
        sa.Column("brief_markdown", sa.Text(), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "version", name="uq_run_brief_version"),
    )
    with op.batch_alter_table("action_brief_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_brief_records_analysis_run_id"), ["analysis_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_action_brief_records_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_action_brief_run_latest", ["analysis_run_id", "is_latest"], unique=False)

    op.create_table(
        "gap_diagnosis_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("gap_type", sa.String(length=100), nullable=False),
        sa.Column("detected", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("evidence_tag", sa.String(length=50), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=False),
        sa.Column("evidence_refs_json", sa.JSON(), nullable=False),
        sa.Column("missing_evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "gap_type", name="uq_run_gap_type"),
    )
    with op.batch_alter_table("gap_diagnosis_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_gap_diagnosis_records_analysis_run_id"),
            ["analysis_run_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_gap_diagnosis_records_created_at"), ["created_at"], unique=False)

    op.create_table(
        "product_readiness_checks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("internal_detail", sa.Text(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_readiness_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_readiness_checks_analysis_run_id"),
            ["analysis_run_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_product_readiness_checks_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_readiness_checks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_product_readiness_checks_status"), ["status"], unique=False)
        batch_op.create_index("ix_readiness_run_code", ["analysis_run_id", "code"], unique=False)
        batch_op.create_index("ix_readiness_status_observed", ["status", "observed_at"], unique=False)

    op.create_table(
        "review_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=50), nullable=False),
        sa.Column("reviewer", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_decisions_analysis_run_id"), ["analysis_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_decisions_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_review_run_created", ["analysis_run_id", "created_at"], unique=False)

    op.create_table(
        "score_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("score_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("components_json", sa.JSON(), nullable=False),
        sa.Column("missing_evidence_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_run_id", "score_type", name="uq_run_score_type"),
    )
    with op.batch_alter_table("score_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_score_records_analysis_run_id"), ["analysis_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_score_records_created_at"), ["created_at"], unique=False)

    op.create_table(
        "export_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("action_brief_id", sa.String(length=36), nullable=True),
        sa.Column("export_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("storage_path", sa.String(length=2048), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_brief_id"], ["action_brief_records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("export_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_export_records_analysis_run_id"), ["analysis_run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_export_records_created_at"), ["created_at"], unique=False)
        batch_op.create_index("ix_export_run_type", ["analysis_run_id", "export_type"], unique=False)

    op.create_table(
        "nvidia_mapping_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("analysis_run_id", sa.String(length=36), nullable=False),
        sa.Column("gap_record_id", sa.String(length=36), nullable=True),
        sa.Column("technology_name", sa.String(length=255), nullable=False),
        sa.Column("addresses_gap", sa.String(length=100), nullable=False),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column("recommendation_action", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("details_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_run_id"], ["analysis_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["gap_record_id"], ["gap_diagnosis_records.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("nvidia_mapping_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_nvidia_mapping_records_analysis_run_id"),
            ["analysis_run_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_nvidia_mapping_records_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_nvidia_mapping_records_gap_record_id"), ["gap_record_id"], unique=False)
        batch_op.create_index(
            "ix_nvidia_mapping_run_gap_technology",
            ["analysis_run_id", "addresses_gap", "technology_name"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nvidia_mapping_records", schema=None) as batch_op:
        batch_op.drop_index("ix_nvidia_mapping_run_gap_technology")
        batch_op.drop_index(batch_op.f("ix_nvidia_mapping_records_gap_record_id"))
        batch_op.drop_index(batch_op.f("ix_nvidia_mapping_records_created_at"))
        batch_op.drop_index(batch_op.f("ix_nvidia_mapping_records_analysis_run_id"))

    op.drop_table("nvidia_mapping_records")
    with op.batch_alter_table("export_records", schema=None) as batch_op:
        batch_op.drop_index("ix_export_run_type")
        batch_op.drop_index(batch_op.f("ix_export_records_created_at"))
        batch_op.drop_index(batch_op.f("ix_export_records_analysis_run_id"))

    op.drop_table("export_records")
    with op.batch_alter_table("score_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_score_records_created_at"))
        batch_op.drop_index(batch_op.f("ix_score_records_analysis_run_id"))

    op.drop_table("score_records")
    with op.batch_alter_table("review_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_review_run_created")
        batch_op.drop_index(batch_op.f("ix_review_decisions_created_at"))
        batch_op.drop_index(batch_op.f("ix_review_decisions_analysis_run_id"))

    op.drop_table("review_decisions")
    with op.batch_alter_table("product_readiness_checks", schema=None) as batch_op:
        batch_op.drop_index("ix_readiness_status_observed")
        batch_op.drop_index("ix_readiness_run_code")
        batch_op.drop_index(batch_op.f("ix_product_readiness_checks_status"))
        batch_op.drop_index(batch_op.f("ix_product_readiness_checks_created_at"))
        batch_op.drop_index(batch_op.f("ix_product_readiness_checks_code"))
        batch_op.drop_index(batch_op.f("ix_product_readiness_checks_analysis_run_id"))

    op.drop_table("product_readiness_checks")
    with op.batch_alter_table("gap_diagnosis_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_gap_diagnosis_records_created_at"))
        batch_op.drop_index(batch_op.f("ix_gap_diagnosis_records_analysis_run_id"))

    op.drop_table("gap_diagnosis_records")
    with op.batch_alter_table("action_brief_records", schema=None) as batch_op:
        batch_op.drop_index("ix_action_brief_run_latest")
        batch_op.drop_index(batch_op.f("ix_action_brief_records_created_at"))
        batch_op.drop_index(batch_op.f("ix_action_brief_records_analysis_run_id"))

    op.drop_table("action_brief_records")
    with op.batch_alter_table("startup_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_startup_evidence_startup_id"))
        batch_op.drop_index("ix_startup_evidence_startup_collected")
        batch_op.drop_index(batch_op.f("ix_startup_evidence_source_url"))
        batch_op.drop_index(batch_op.f("ix_startup_evidence_evidence_kind"))
        batch_op.drop_index(batch_op.f("ix_startup_evidence_created_at"))

    op.drop_table("startup_evidence")
    with op.batch_alter_table("analysis_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_analysis_runs_status"))
        batch_op.drop_index(batch_op.f("ix_analysis_runs_startup_id"))
        batch_op.drop_index("ix_analysis_runs_startup_created")
        batch_op.drop_index(batch_op.f("ix_analysis_runs_created_at"))

    op.drop_table("analysis_runs")
    with op.batch_alter_table("startups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_startups_status"))
        batch_op.drop_index(batch_op.f("ix_startups_name"))
        batch_op.drop_index(batch_op.f("ix_startups_created_at"))

    op.drop_table("startups")
    # ### end Alembic commands ###
